global:
  style: "日本のkawaii手描き風、太めの黒輪郭、パステル調"
  layout: "3×3正方形グリッド、透明キャンバス"
  margin: "キャラ周囲に十分な余白、分割しやすい配置"
  background: "シンプル。必要なら最小限の小物のみ"
  speech: "セリフを含める、日本語で、短いものが好ましい"
  character_placement: "キャラは1体または2体、中央に配置、外周は透明"