global:
  style: "日本のkawaii手描き風、太めの滑らかで明確な黒色(#3e3e3e)輪郭線、パステル調"
  layout: "3×3正方形グリッド、白色(#ffffff)背景、透明色を使用しない"
  margin: "キャラ周囲に十分な余白、分割しやすい配置、シーンの外形は丸に収まる"
  speech: "セリフを含める場合は短い日本語(10文字以内)"
  character_placement: "キャラは1体または2体、中央に配置、外周は透明"