objects:
  うしくん:
    description:
      - "顔は白ベース、右目にだけ濃いグレーのぶち模様（左目側は模様なし）"
      - "鼻先はピンク、輪郭線なし、鼻孔は横長の楕円（長穴）で表現"
      - "黄色い角が2本（丸みあり）"
      - "ネイビーのシングルスーツ（細めラペル）"
      - "落ち着いた or 少し疲れた表情"
      - "所有物に牛の鼻輪をモチーフとしたブランドロゴ"
  ぶたくん:
    description:
      - "顔はピンク色、丸顔、小さな三角耳"
      - "縦穴2つの大きな豚鼻"
      - "くるくる巻いた豚のしっぽ"
      - "茶色のダブルスーツ（広いラペル・ボタン4つ）＋白シャツ"
      - "表情は陽気、おちゃめ、焦り、嬉しさなど豊か"
      - "所有物に豚鼻をモチーフとしたブランドロゴ" 