objects:
  うしくん:
    description:
      - "明るいアイボリー色(#fffaf4)の顔、右耳と右目周辺のみ濃いグレー(#5c5c61)のぶち模様、左耳と左目周辺はぶち模様なし"
      - "淡いピンク色(#f5b9b0)の鼻、鼻と顔の境界には濃い線を禁止、鼻孔は横長の長穴楕円で表現"
      - "柔らかい黄色(#f4d04b)の丸みがあって縞2本を含む角が2本"
      - "濃いネイビー色(#273a63)の細いラペルのシングルスーツ"
      - "落ち着いた、または少し疲れた表情"
      - "所有物に牛の鼻輪をモチーフとしたブランドロゴ"
  ぶたくん:
    description:
      - "薄いピンク色(#fbd1c6)の顔、丸顔、小さな三角耳"
      - "縦穴2つの大きなやや濃いピンク色(#f79b96)の豚鼻"
      - "くるくる巻いた豚のしっぽ"
      - "こげ茶色(#5a3626)の広いラペルで4つボタンのダブルスーツ"
      - "表情は陽気、おちゃめ、焦り、嬉しさなど大げさ"
      - "所有物に豚鼻をモチーフとしたブランドロゴ" 